### ISSUE TITLE
Image upload 

### ISSUE THREAD

**Issue by TanRyu7** [adibud/cits3403-project#10]
David's backend code needs to be fixed so we can upload images in the requests(Top priority)

**Comment by TanRyu7** [comment]
`import os
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from .models import requests
from . import db

main = Blueprint('main', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@main.route("/")
def index():
    return render_template("home.html", user=current_user)

@main.route("/create_request", methods=['GET', 'POST'])
@login_required
def create_request():
    if request.method == 'POST':
        title = request.form.get('title')
        descr = request.form.get('descr')
        quantity = request.form.get('quantity')
        image = None

        if 'image' in request.files:
            file = request.files['image']
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                upload_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                os.makedirs(os.path.dirname(upload_path), exist_ok=True)  # Ensure directory exists
                file.save(upload_path)
                image = filename

        if title and descr and quantity:
            new_req = requests(title=title, descr=descr, quantity=quantity, image=image, user_id=current_user.id)
            db.session.add(new_req)
            db.session.commit()
            flash('Request posted!', category='success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('All fields are required.', category='error')
    return render_template("create_request.html", user=current_user)`

    #this code is working when uploading images into the requests on the website

**Comment by pohhui247** [comment]
I've managed to get the image upload working

**Comment by TanRyu7** [comment]
Nice! thanks
